Vagrant.configure("2") do |config|
  # 공통 설정
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_url = "https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/202212.11.0/providers/virtualbox/unknown/vagrant.box"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

  # 컨트롤러 가상 머신 설정
  config.vm.define "jaehwkimS" do |ctl|
    ctl.vm.hostname = "jaehwkimS"
    ctl.vm.network "private_network", ip: "192.168.56.110"
    ctl.vm.provider "virtualbox" do |vb|
      vb.name = "jaehwkimS"
    end

    # YAML 파일들을 가상 머신에 복사
    ctl.vm.provision "file", source: "./app1-deployment-service.yaml", destination: "/home/vagrant/app1-deployment-service.yaml"
    ctl.vm.provision "file", source: "./app2-deployment-service.yaml", destination: "/home/vagrant/app2-deployment-service.yaml"
    ctl.vm.provision "file", source: "./app3-deployment-service.yaml", destination: "/home/vagrant/app3-deployment-service.yaml"
    ctl.vm.provision "file", source: "./ingress.yaml", destination: "/home/vagrant/ingress.yaml"

    # 서버 설정 스크립트 실행
    ctl.vm.provision "shell", inline: <<-SHELL
      # k3s 설치
      curl -sfL https://get.k3s.io | sh -s - --node-ip 192.168.56.110 --advertise-address 192.168.56.110 --flannel-iface eth1 --write-kubeconfig-mode 644

      # 컨트롤러 노드에서 생성된 인증 토큰을 복사 
      # cp /var/lib/rancher/k3s/server/node-token /vagrant/server-node-token

      # k alias 
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc

      # YAML 파일들을 적용
      # until kubectl get nodes; do sleep 1; done   # Kubernetes 클러스터가 준비될 때까지 대기
      kubectl apply -f /home/vagrant/app1-deployment-service.yaml
      kubectl apply -f /home/vagrant/app2-deployment-service.yaml
      kubectl apply -f /home/vagrant/app3-deployment-service.yaml
      kubectl apply -f /home/vagrant/ingress.yaml
    SHELL
  end
end
