Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_url = "https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/202212.11.0/providers/virtualbox/unknown/vagrant.box"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.gui = true
  end

  config.vm.define "jaehwkimS" do |ctl|
    ctl.vm.hostname = "jaehwkimS"
    ctl.vm.network "private_network", ip: "192.168.56.110"
    ctl.vm.provider "virtualbox" do |vb|
      vb.name = "jaehwkimS"
    end

    # YAML 파일들을 가상 머신에 복사
    ['app1-deployment-service', 'app2-deployment-service', 'app3-deployment-service', 'ingress'].each do |file|
      ctl.vm.provision "file", source: "./yaml/#{file}.yaml", destination: "/home/vagrant/#{file}.yaml"
    end

    # 서버 설정 스크립트 실행
    ctl.vm.provision "shell", path: "shell/provision.sh"
  end
end
